;$(document).ready(function(){(function(){var greet=$("#greeting");var nowHour=new Date().getHours();if(nowHour>=18){greet.html("晚安，您好")}else if(nowHour>=12){greet.html("午安，您好")}else if(nowHour>=6){greet.html("早安，您好")}else{greet.html("現在是凌晨，請早點休息")}}());$(".changeBookImage").mouseover(function(){var bookName=$(this).attr("name");var imageContainerId=bookName.substr(0,bookName.length-1);$("#"+imageContainerId).css("background-image","url(images/books/"+imageContainerId+"/"+bookName+".png)")});$('.owl-carousel').owlCarousel({loop:!0,center:!1,autoplay:!0,autoplayTimeout:3000,autoplayHoverPause:!0,responsiveClass:!0,responsive:{0:{items:1,nav:!1},768:{items:3,margin:40,nav:!0},1024:{item:3,margin:60,nav:!0}}});window.sr=ScrollReveal({duration:800,distance:"100px",reset:!0});sr.reveal(".js-fadeInUp");sr.reveal(".js-fadeInRight",{origin:"left"});sr.reveal(".js-fadeInLeft",{origin:"right"});sr.reveal(".ranking-item.js-fadeInOrder",100);sr.reveal(".other-item.js-fadeInOrder ",100)
var user=[{account:"abc@gmail.com",password:"123"}];localStorage.setItem("user",JSON.stringify(user));var loginMenu=$("#loginMenu");$("#loginBtn").click(function(){changeToLogup();loginMenu.css("visibility","visible");loginMenu.css("opacity","1")});loginMenu.click(alreadyLogIn);$(".login-container").click(function(e){e.stopPropagation()});$("#login-type").click(function(e){var targetText=e.target.textContent;if(targetText==="註冊"){changeToLogup()}else if(targetText==="登入"){changeToLogin()}});function changeToLogup(){$("#changeLoginType").attr("class","u-mb-32");var logupBtn=document.getElementById("registOrCheck");logupBtn.value="註冊"}
function changeToLogin(){$("#changeLoginType").attr("class","u-mb-32 u-display-n");var loginBtn=document.getElementById("registOrCheck");loginBtn.value="登入"}
$("#registOrCheck").click(function(){var success;if(this.value==="註冊"){success=checkUser(1,$("#account")[0].value,$("#password")[0].value,$("#password2")[0].value)}else if(this.value==="登入"){success=checkUser(0,$("#account")[0].value,$("#password")[0].value,$("#password2")[0].value)}
switch(success){case "registSuccess":hint("恭喜您，註冊成功。","green");alreadyLogIn();break;case "registRepeat":hint("帳號重複，請重新註冊。","red");break;case "registFail":hint("第二次密碼輸入不同，請重新輸入。","red");break;case "loginSuccess":hint("登入成功。","green");alreadyLogIn();break;case "loginFail":hint("帳號或密碼有誤。","red");break;case "acountFailed":hint("帳號不符合email格式","red");break}});$("#cancel").click(alreadyLogIn);function hint(hintText,hintColor){$("#registHint").text(hintText);if(hintColor){$("#registHint").css("color",hintColor)}}
function alreadyLogIn(){$("#account")[0].value="";$("#password")[0].value="";$("#password2")[0].value="";hint("");loginMenu.css("visibility","hidden");loginMenu.css("opacity","0")}
function addUser(userAccount,userPassword,checkPassword){var temp={account:userAccount,password:userPassword};user.push(temp);localStorage.setItem("user",JSON.stringify(user))}
function checkUser(addOrcheck,userAccount,userPassword,checkPassword){var temp=JSON.parse(localStorage.getItem("user"));var reg=new RegExp(/^\w+((\-\w+)|(\.\w+))*\@\w+((\.|\-)\w+)*\.[A-Za-z]+$/);if(!userAccount.match(reg)){return"acountFailed"}
for(var i=0;i<temp.length;i ++){if(addOrcheck===0){if(temp[i].account===userAccount){if(temp[i].password===userPassword){return"loginSuccess"}}}else if(addOrcheck===1){if(temp[i].account===userAccount){return"registRepeat"}
if(userPassword===checkPassword){addUser(userAccount,userPassword);return"registSuccess"}else{return"registFail"}}}
return"loginFail"}});